tailwind.config = {
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-tertiary-fixed": "#410001",
        "tertiary-fixed": "#ffdad5",
        "on-primary": "#ffffff",
        "primary-fixed-dim": "#4ae176",
        "surface-container-high": "#dce9ff",
        tertiary: "#9e4036",
        "surface-dim": "#cbdbf5",
        "on-tertiary-fixed-variant": "#7f2a21",
        error: "#ba1a1a",
        secondary: "#565e74",
        "on-secondary-fixed": "#131b2e",
        "on-secondary-container": "#5c647a",
        background: "#f8f9ff",
        outline: "#6d7b6c",
        "on-primary-fixed-variant": "#005321",
        "surface-container": "#e5eeff",
        "error-container": "#ffdad6",
        "on-secondary-fixed-variant": "#3f465c",
        "on-primary-container": "#004b1e",
        primary: "#006e2f",
        "on-error": "#ffffff",
        "on-surface": "#0b1c30",
        "surface-variant": "#d3e4fe",
        "inverse-on-surface": "#eaf1ff",
        "inverse-surface": "#213145",
        "surface-container-lowest": "#ffffff",
        "on-surface-variant": "#3d4a3d",
        "on-secondary": "#ffffff",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#ff8b7c",
        "secondary-container": "#dae2fd",
        "outline-variant": "#bccbb9",
        "surface-tint": "#006e2f",
        surface: "#f8f9ff",
        "surface-container-highest": "#d3e4fe",
        "surface-bright": "#f8f9ff",
        "secondary-fixed": "#dae2fd",
        "tertiary-fixed-dim": "#ffb4a9",
        "on-background": "#0b1c30",
        "on-primary-fixed": "#002109",
        "secondary-fixed-dim": "#bec6e0",
        "on-error-container": "#93000a",
        "surface-container-low": "#eff4ff",
        "on-tertiary-container": "#76231b",
        "primary-fixed": "#6bff8f",
        "primary-container": "#22c55e",
        "inverse-primary": "#4ae176",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        xs: "4px",
        sm: "8px",
        xl: "48px",
        unit: "4px",
        gutter: "24px",
        "container-max": "1280px",
        md: "16px",
        lg: "24px",
      },
      fontFamily: {
        h2: ["Inter"],
        h3: ["Inter"],
        "body-sm": ["Inter"],
        "body-lg": ["Inter"],
        "label-caps": ["Inter"],
        h1: ["Inter"],
        "body-md": ["Inter"],
      },
      fontSize: {
        h2: [
          "30px",
          {
            lineHeight: "38px",
            letterSpacing: "-0.01em",
            fontWeight: "600",
          },
        ],
        h3: [
          "24px",
          {
            lineHeight: "32px",
            letterSpacing: "0",
            fontWeight: "600",
          },
        ],
        "body-sm": [
          "14px",
          {
            lineHeight: "20px",
            fontWeight: "400",
          },
        ],
        "body-lg": [
          "18px",
          {
            lineHeight: "28px",
            fontWeight: "400",
          },
        ],
        "label-caps": [
          "12px",
          {
            lineHeight: "16px",
            letterSpacing: "0.05em",
            fontWeight: "600",
          },
        ],
        h1: [
          "40px",
          {
            lineHeight: "48px",
            letterSpacing: "-0.02em",
            fontWeight: "700",
          },
        ],
        "body-md": [
          "16px",
          {
            lineHeight: "24px",
            fontWeight: "400",
          },
        ],
      },
    },
  },
};
