spring.application.name=ucab-services
# PostgreSQL DataSource Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/Base_de_Datos
spring.datasource.username=postgres
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver
# Hibernate DDL Auto (update for development)
spring.jpa.hibernate.ddl-auto=none
# Show SQL in console
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

server.port=8081

# Activar perfil local para que cada quien tenga su configuracion de BD sin pisarse en Github
spring.profiles.active=local